FROM apache/airflow:3.0.6

COPY requirements.txt /tmp/bayan-requirements.txt

RUN pip install --no-cache-dir \
    -r /tmp/bayan-requirements.txt

COPY 02_code/02_src /opt/airflow/bayan

ENV PYTHONPATH="/opt/airflow/bayan:${PYTHONPATH}"
